#!/usr/bin/env bash

set -e -o pipefail

source _toolbox_lib.sh

docker-compose ps

SERVICES=$(docker-compose ps -q)
while read -r CONTAINER_ID; do
  CONTAINER_NAME=$(docker inspect --format="{{.Name}}" "$CONTAINER_ID")
  echo
  echo "$CONTAINER_NAME"
  echo "> docker logs --tail \"${DOCKER_LOGS_TAIL_COUNT}\" \"$CONTAINER_ID\""
  docker logs --tail "${DOCKER_LOGS_TAIL_COUNT}" "$CONTAINER_ID"
done <<< "$SERVICES"