#!/usr/bin/env bash

set -e -o pipefail

source _toolbox_lib.sh

FROM_PERSON=${1:-alice}
TO_PERSON=${2:-bob}

connect_bitcoin_nodes() {
  local role
  role=$(get_role "$TO_PERSON")
  if [[ "$role" != "bitcoin" ]]; then
    echo_err "both nodes to have the same role, '$TO_PERSON' has role '$role' but 'bitcoin' was expected"
    exit 2
  fi

  # note: we don't have to check for flavor here, both bitcoind and btcd have compatible 'addnode' cli interface
  "$FROM_PERSON" addnode "$TO_PERSON" onetry
  # note we need to generate one block to trigger potential block sync
  # not sure what is the issue, but this might be related https://bitcoin.stackexchange.com/q/27055/875
  generate 1 "$FROM_PERSON"
}

connect_ln_nodes() {
  local role
  role=$(get_role "$TO_PERSON")
  if [[ "$role" != "ln" ]]; then
    echo_err "both nodes to have the same role, '$TO_PERSON' has role '$role' but 'ln' was expected"
    exit 2
  fi

  local to_flavor
  to_flavor=$(get_flavor "$TO_PERSON")
  local port
  case "$to_flavor" in
    lnd) port="$LND_P2P_PORT";;
    lightning) port="$LIGHTNING_P2P_PORT";;
    eclair) port="$ECLAIR_P2P_PORT";;
    *) echo_err "unsupported flavor type '$flavor' for '$TO_PERSON'"; exit 1; ;;
  esac

  TO_PERSON_CONNECTION=$(ln_connect_string "$TO_PERSON"):"$port"
  if [[ -z "$TO_PERSON_CONNECTION" ]]; then
    echo_err "failed to format connection string for '$TO_PERSON'"
    exit 1
  fi

  local from_flavor
  from_flavor=$(get_flavor "$FROM_PERSON")
  case "$from_flavor" in
    lnd|lightning) "$FROM_PERSON" connect "$TO_PERSON_CONNECTION" ;;
    eclair) "$FROM_PERSON" connect --uri="$TO_PERSON_CONNECTION" ;;
    *) echo_err "unsupported flavor type '$flavor' for '$FROM_PERSON'"; exit 1; ;;
  esac
}

ROLE=$(get_role "$FROM_PERSON")
case "$ROLE" in
  bitcoin) connect_bitcoin_nodes ;;
  ln) connect_ln_nodes ;;
  *) echo_err "unsupported role type '$ROLE' for '$FROM_PERSON'"; exit 1; ;;
esac
