#!/usr/bin/env bash

source _lib.sh

AMOUNT=${1:-100} # minimal amount
FAUCET_ADDR=${FAUCET_ADDR:?required}

BLOCKS_NEEDED=$(compute "floor(${AMOUNT} / 50) + 1")
echo "mining ${BLOCKS_NEEDED} blocks on master bitcoin node"

# generate blocks on master node
generate ${BLOCKS_NEEDED}

# mine blocks to mature coinbase transactions
generate ${COINBASE_MATURITY}
