#!/usr/bin/env bash

set -e -o pipefail

source _lib.sh

AMOUNT_BTC=${1:-100} # minimal amount
FAUCET_ADDR=${FAUCET_ADDR:?required}

BLOCK_SUBSIDY=50 # we assume a young blockchain with 50 BTC per block
BLOCKS_NEEDED=$(compute "floor(${AMOUNT_BTC} / ${BLOCK_SUBSIDY}) + 1")
echo "mining ${BLOCKS_NEEDED} blocks on master bitcoin node"

# generate blocks on master node
generate "${BLOCKS_NEEDED}"

# mine blocks to mature coinbase transactions
generate "${COINBASE_MATURITY}"
