#!/usr/bin/env bash

set -e -o pipefail

source _toolbox_lib.sh

NUM_BLOCKS=${1:-1} # number of blocks
WHERE=${2} # (optional) bitcoin node which should mine it, defaults to master bitcoin node
FAUCET_ADDR=${FAUCET_ADDR:?required}

if [[ -z "$WHERE" ]]; then
  WHERE=$(lookup_service 1 role bitcoin)
fi

BLOCKS="blocks"
if [[ "$NUM_BLOCKS" = 1 ]]; then
  BLOCKS="block"
fi

echo "generating $NUM_BLOCKS $BLOCKS via $WHERE ..."
FLAVOR=$(get_flavor "$WHERE")
case "$FLAVOR" in
  bitcoind)
    "$WHERE" generatetoaddress "${NUM_BLOCKS}" "${FAUCET_ADDR}" > /dev/null
    ;;
  btcd)
    # note: faucet addr was passed to btcd daemon as config
    "$WHERE" generate "${NUM_BLOCKS}" > /dev/null
    ;;
  *) echo_err "unsupported flavor type '$FLAVOR' for '$WHERE'"; exit 1; ;;
esac