#!/usr/bin/env bash

source _lib.sh

NUM_BLOCKS=${1:-1} # number of blocks
FAUCET_ADDR=${FAUCET_ADDR:?required}

if is_btcd_master; then
  btcctl generate ${NUM_BLOCKS} # note: faucet addr was passed to btcd daemon as config
else
  bitcoin-cli generatetoaddress ${NUM_BLOCKS} ${FAUCET_ADDR}
fi