#!/usr/bin/env bash

# see https://stackoverflow.com/a/55155992/84283
docker ps -q | xargs -n 1 docker inspect --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}} {{ .Name }}' | sed 's/ \// /'