#!/usr/bin/env bash

set -e -o pipefail

source _toolbox_lib.sh

PERSON=${1:-alice}

FLAVOR=$(get_flavor "$PERSON")
case "$FLAVOR" in
  lnd)
    BALANCE=$("$PERSON" channelbalance | jq -r ".balance")
    if [[ -z "$BALANCE" ]]; then
      echo "-1"
    fi
    echo "$BALANCE" | sat2btc
    ;;
  lightning)
    "$PERSON" listfunds | jq '[.channels[].channel_sat] | add' | sat2btc
    ;;
  eclair)
    "$PERSON" channels | jq '[.[].data.commitments.localCommit.spec.toLocalMsat] | add' | msat2btc
    ;;
  *) echo_err "unsupported flavor type '$FLAVOR' for '$PERSON'"; exit 1; ;;
esac