#!/usr/bin/env bash

set -e -o pipefail

source _toolbox_lib.sh

PERSON=${1:-alice}

FLAVOR=$(get_flavor "$PERSON")
case "$FLAVOR" in
  lnd) exec "$PERSON" newaddress p2wkh | jq -e -r ".address" ;;
  lightning) exec "$PERSON" newaddr bech32 | jq -e -r ".address" ;;
  eclair) exec "$PERSON" newaddr bech32 ;;
  *) echo_err "unsupported flavor type '$FLAVOR' for '$PERSON'"; exit 1; ;;
esac