#!/usr/bin/env bash

set -e -o pipefail

source _toolbox_lib.sh

FROM_PERSON=${1:-alice}
TO_PERSON=${2:-bob}
AMOUNT_BTC=${3:-0.1}

TO_PERSON_PUBKEY=$(pubkey "${TO_PERSON}")
AMOUNT_SAT=$(echo "$AMOUNT_BTC" | btc2sat)

FLAVOR=$(get_flavor "$FROM_PERSON")
case "$FLAVOR" in
  lnd) ${FROM_PERSON} openchannel "--node_key=${TO_PERSON_PUBKEY}" "--local_amt=${AMOUNT_SAT}" ;;
  lightning) ${FROM_PERSON} fundchannel "$TO_PERSON_PUBKEY" "$AMOUNT_SAT" 4000;;
  eclair) ${FROM_PERSON} open "--nodeId=${TO_PERSON_PUBKEY}" "--fundingSatoshis=${AMOUNT_SAT}" ;;
  *) echo_err "unsupported flavor type '$FLAVOR' for host '$FROM_PERSON'"; exit 1; ;;
esac

generate "${CHANNEL_CONF_COUNT}"
