#!/usr/bin/env bash

source _lib.sh

FROM_PERSON=${1:-alice}
TO_PERSON=${2:-bob}
AMOUNT_BTC=${3:-0.01}

PAY_REQ=$(invoice ${TO_PERSON} ${AMOUNT_BTC} | jq ".pay_req" | unquote)

set -x
${FROM_PERSON} sendpayment --force --pay_req=${PAY_REQ}