#!/usr/bin/env bash

source _lib.sh

PERSON=${1:-alice}
TEMP_JSON_FILE=/tmp/simverse_pubkey_info.json

err_report() {
  echo_err "error on line $(caller)"
  echo_err "see '$TEMP_JSON_FILE'"
  return 1
}

trap err_report ERR

${PERSON} getinfo > ${TEMP_JSON_FILE}

FLAVOR=$(get_flavor "$PERSON")
case "$FLAVOR" in
  lnd) KEY="identity_pubkey" ;;
  lightning) KEY="id" ;;
  *) echo_err "unsupported flavor type '$FLAVOR' for '$PERSON'"; exit 1; ;;
esac

jq ".${KEY}" ${TEMP_JSON_FILE} | unquote
