#!/usr/bin/env bash

set -e -o pipefail

source _lib.sh

PERSON=${1:-alice}

err_report() {
  echo_err "error on line $(caller)"
  if [[ -n "$INFO" ]]; then
    echo_err "getinfo output:"
    echo_err "$INFO"
  fi
  return 1
}

trap err_report ERR

INFO=$("$PERSON" getinfo)

FLAVOR=$(get_flavor "$PERSON")
case "$FLAVOR" in
  lnd) KEY="identity_pubkey" ;;
  lightning) KEY="id" ;;
  eclair) KEY="nodeId" ;;
  *) echo_err "unsupported flavor type '$FLAVOR' for '$PERSON'"; exit 1; ;;
esac

echo -n "$INFO" | jq -r ".${KEY}"
