#!/usr/bin/env bash

set -e -o pipefail

source _lib.sh

PERSON=${1:-alice}
AMOUNT_BTC=${2:-0.01}
LABEL=${3:-$PERSON invoicing $AMOUNT_BTC BTC [#$RANDOM]}
DESCRIPTION=${4:-without description}

FLAVOR=$(get_flavor "$PERSON")
case "$FLAVOR" in
  lnd)
    AMOUNT_SAT=$(echo "$AMOUNT_BTC" | btc2sat)
    # TODO: add support for LABEL/DESCRIPTION
    "$PERSON" addinvoice "--amt=${AMOUNT_SAT}" | jq -r ".pay_req"
    ;;
  lightning)
    AMOUNT_MSAT=$(echo "$AMOUNT_BTC" | btc2msat)
    "$PERSON" invoice "${AMOUNT_MSAT}" "$LABEL" "$DESCRIPTION" | jq -r ".bolt11"
    ;;
  eclair)
    AMOUNT_MSAT=$(echo "$AMOUNT_BTC" | btc2msat)
    "$PERSON" createinvoice "--description=$DESCRIPTION" "--amountMsat=${AMOUNT_MSAT}" | jq -r ".serialized"
    ;;
  *) echo_err "unsupported flavor type '$FLAVOR' for '$PERSON'"; exit 1; ;;
esac
