version: '3.7'

# https://docs.docker.com/compose/compose-file/#extension-fields
x-shared: &shared
  networks:
    - ${SIMVERSE_DOCKER_NETWORK_PREFIX}${SIMNET_NAME}_network
  healthcheck:
    test: "nc -z localhost ${SERVICE_READY_PORT}"
    interval: 5s
    timeout: 10s
    retries: 3
    start_period: 2m
  privileged: true # needed for dlv attach
  stop_grace_period: 1m
  security_opt:
    - seccomp:unconfined # https://github.com/arrisray/secql/commit/19b8e85c270b888cecc3a0364b7956ba9e0f5334

networks:
  ${SIMVERSE_DOCKER_NETWORK_PREFIX}${SIMNET_NAME}_network:
    driver: bridge
    name: ${SIMVERSE_DOCKER_NETWORK_PREFIX}${SIMNET_NAME}_network

services:

  pre:
    <<: *shared
    image: ${SIMVERSE_DOCKER_IMAGE_PREFIX}${SIMNET_NAME}_pre
    container_name: ${SIMVERSE_DOCKER_CONTAINER_PREFIX}${SIMNET_NAME}_pre
    command: ["run"]
    stop_signal: SIGINT # needed for python server
    build:
      context: .
      dockerfile: docker/pre/Dockerfile
      args:
        - PRE_DOCKER_BUILDTIME_IMAGE=$PRE_DOCKER_BUILDTIME_IMAGE
        - PRE_DOCKER_RUNTIME_IMAGE=$PRE_DOCKER_RUNTIME_IMAGE
    ports:
      - $SIMVERSE_HOST_BIND$SERVICE_READY_PORT_ON_HOST:$SERVICE_READY_PORT # readiness signal port
    volumes:
      # !DANGER! when touching this, review cookbook.sh > prepare_pre_volumes
      - ./_volumes/certs:/home/simnet/certs # shared certificates
    environment:
      - CONTAINER_NAME=pre
      - REPORT_ENV=${SIMVERSE_REPORT_ENV}
      - SERVICE_READY_PORT=${SERVICE_READY_PORT}
      - CONTAINER_SERVICE_PORT=${CONTAINER_SERVICE_PORT}
      - SIMNET_NAME=${SIMNET_NAME}
    $SIMVERSE_EXTRA_SERVICE_CONFIG
