#!/usr/bin/env bash

# this was generated by https://github.com/travis-ci/travis-build

TRAVIS_ANSI_CLEAR="\033[0K"

case $(uname | tr '[:upper:]' '[:lower:]') in
linux*)
  export TRAVIS_OS_NAME=linux
  ;;
darwin*)
  export TRAVIS_OS_NAME=osx
  ;;
msys*)
  export TRAVIS_OS_NAME=windows
  ;;
*)
  export TRAVIS_OS_NAME=notset
  ;;
esac

travis_time_start() {
  TRAVIS_TIMER_ID="$(printf %08x $((RANDOM * RANDOM)))"
  TRAVIS_TIMER_START_TIME="$(travis_nanoseconds)"
  export TRAVIS_TIMER_ID TRAVIS_TIMER_START_TIME
  echo -en "travis_time:start:$TRAVIS_TIMER_ID\r${TRAVIS_ANSI_CLEAR}"
}

travis_time_finish() {
  local travis_timer_end_time
  travis_timer_end_time="$(travis_nanoseconds)"
  local duration
  duration="$((travis_timer_end_time - TRAVIS_TIMER_START_TIME))"
  echo -en "travis_time:end:${TRAVIS_TIMER_ID}:start=${TRAVIS_TIMER_START_TIME},finish=${travis_timer_end_time},duration=${duration}\r${TRAVIS_ANSI_CLEAR}"
}

travis_nanoseconds() {
  local cmd='date'
  local format='+%s%N'

  if hash gdate >/dev/null 2>&1; then
    cmd='gdate'
  elif [[ "${TRAVIS_OS_NAME}" == osx ]]; then
    format='+%s000000000'
  fi

  "${cmd}" -u "${format}"
}

travis_fold() {
  local action=$1
  local name=$2
  echo -en "travis_fold:${action}:${name}\r${TRAVIS_ANSI_CLEAR}"
}

travis_section() {
  local action=$1
  if [[ "$action" == "start" ]]; then
    travis_fold "$@"
    travis_time_start
  else
    travis_time_finish
    travis_fold "$@"
  fi
}