#!/usr/bin/env bash

. "$(dirname "${BASH_SOURCE[0]}")/helpers/_config.sh" || true || . helpers/_config.sh

cd "$THIS_DIR"

if [[ ! -d "$VOLUMES_DIR" ]]; then
  mkdir -p "$VOLUMES_DIR"
fi

exec docker-compose "$@"
